import { Game } from '../components/GamePicker'

export const games: Game[][] = [
	[
		{spread: -2.5, away: "NYJ", home: "MIN"},
		{spread: -3.5, away: "CAR", home: "CHI"},
		{spread: 2.5, away: "BAL", home: "CIN"},
		{spread: 1.5, away: "BUF", home: "HOU"},
		{spread: -2.5, away: "IND", home: "JAX"},
		{spread: -1, away: "MIA", home: "NE"},
		{spread: -3, away: "CLE", home: "WSH"},
		{spread: -2.5, away: "LV", home: "DEN"},
		{spread: -7, away: "ARI", home: "SF"},
		{spread: 3, away: "GB", home: "LAR"},
		{spread: -6, away: "NYG", home: "SEA"},
		{spread: -2, away: "DAL", home: "PIT"},
		{spread: -5.5, away: "NO", home: "KC"}
	],
	[
		{spread: -1, away: "JAX", home: "CHI"},
		{spread: -5.5, away: "ARI", home: "GB"},
		{spread: -2.5, away: "IND", home: "TEN"},
		{spread: +6.5, away: "HOU", home: "NE"},
		{spread: +3.5, away: "TB", home: "NO"},
		{spread: -9, away: "CLE", home: "PHI"},
		{spread: -6.5, away: "WSH", home: "BAL"},
		{spread: +3, away: "LAC", home: "DEN"},
		{spread: +3, away: "PIT", home: "LV"},
		{spread: +3, away: "DET", home: "DAL"},
		{spread: +6, away: "ATL", home: "CAR"},
		{spread: +3.5, away: "CIN", home: "NYG"},
		{spread: +2.5, away: "BUF", home: "NYJ"},
	],
	[
		{spread: -6, away: "NE", home: "JAX"},
		{spread: -3, away: "SEA", home: "ATL"},
		{spread: -9.5, away: "TEN", home: "BUF"},
		{spread: 5.5, away: "CIN", home: "CLE"},
		{spread: -3, away: "HOU", home: "GB"},
		{spread: -3, away: "MIA", home: "IND"},
		{spread: -1.5, away: "DET", home: "MIN"},
		{spread: 3.5, away: "PHI", home: "NYG"},
		{spread: -7, away: "LV", home: "LAR"},
		{spread: -8, away: "CAR", home: "WSH"},
		{spread: -1.5, away: "KC", home: "SF"},
		{spread: 1.5, away: "NYJ", home: "PIT"},
		{spread: 3.5, away: "BAL", home: "TB"},
		{spread: 2, away: "LAC", home: "ARI"},
	],
	[
		{spread: 8.5, away: "BAL", home: "CLE"},
		{spread: -11, away: "TEN", home: "DET"},
		{spread: -5, away: "IND", home: "HOU"},
		{spread: 3.5, away: "GB", home: "JAX"},
		{spread: -3.5, away: "ARI", home: "MIA"},
		{spread: 7, away: "NYJ", home: "NE"},
		{spread: 2.5, away: "ATL", home: "TB"},
		{spread: -2.5, away: "PHI", home: "CIN"},
		{spread: -7.5, away: "NO", home: "LAC"},
		{spread: 3, away: "BUF", home: "SEA"},
		{spread: 2.5, away: "CHI", home: "WSH"},
		{spread: -10, away: "CAR", home: "DEN"},
		{spread: 9.5, away: "KC", home: "LV"},
		{spread: -4, away: "DAL", home: "SF"},
		{spread: -6, away: "NYG", home: "PIT"},
	],
]

export const weekIdToWeekNumber: string[] = [
	"5",
	"6",
	"7",
	"8"
]
