import { Game } from '../components/GamePicker'

export const games: Game[][] = [
	[
		{spread: -2.5, away: "NYJ", home: "MIN"},
		{spread: -3.5, away: "CAR", home: "CHI"},
		{spread: 2.5, away: "BAL", home: "CIN"},
		{spread: 1.5, away: "BUF", home: "HOU"},
		{spread: -2.5, away: "IND", home: "JAX"},
		{spread: -1, away: "MIA", home: "NE"},
		{spread: -3, away: "CLE", home: "WSH"},
		{spread: -2.5, away: "LV", home: "DEN"},
		{spread: -7, away: "ARI", home: "SF"},
		{spread: 3, away: "GB", home: "LAR"},
		{spread: -6, away: "NYG", home: "SEA"},
		{spread: -2, away: "DAL", home: "PIT"},
		{spread: -5.5, away: "NO", home: "KC"}
	],
	[
		{spread: -1, away: "JAX", home: "CHI"},
		{spread: -5.5, away: "ARI", home: "GB"},
		{spread: -2.5, away: "IND", home: "TEN"},
		{spread: +6.5, away: "HOU", home: "NE"},
		{spread: +3.5, away: "TB", home: "NO"},
		{spread: -9, away: "CLE", home: "PHI"},
		{spread: -6.5, away: "WSH", home: "BAL"},
		{spread: +3, away: "LAC", home: "DEN"},
		{spread: +3, away: "PIT", home: "LV"},
		{spread: +3, away: "DET", home: "DAL"},
		{spread: +6, away: "ATL", home: "CAR"},
		{spread: +3.5, away: "CIN", home: "NYG"},
		{spread: +2.5, away: "BUF", home: "NYJ"},
	],
	[
		{spread: -6, away: "NE", home: "JAX"},
		{spread: -3, away: "SEA", home: "ATL"},
		{spread: -9.5, away: "TEN", home: "BUF"},
		{spread: 5.5, away: "CIN", home: "CLE"},
		{spread: -3, away: "HOU", home: "GB"},
		{spread: -3, away: "MIA", home: "IND"},
		{spread: -1.5, away: "DET", home: "MIN"},
		{spread: 3.5, away: "PHI", home: "NYG"},
		{spread: -7, away: "LV", home: "LAR"},
		{spread: -8, away: "CAR", home: "WSH"},
		{spread: -1.5, away: "KC", home: "SF"},
		{spread: 1.5, away: "NYJ", home: "PIT"},
		{spread: 3.5, away: "BAL", home: "TB"},
		{spread: 2, away: "LAC", home: "ARI"},
	],
	[
		{spread: 8.5, away: "BAL", home: "CLE"},
		{spread: -11, away: "TEN", home: "DET"},
		{spread: -5, away: "IND", home: "HOU"},
		{spread: 3.5, away: "GB", home: "JAX"},
		{spread: -3.5, away: "ARI", home: "MIA"},
		{spread: 7, away: "NYJ", home: "NE"},
		{spread: 2.5, away: "ATL", home: "TB"},
		{spread: -2.5, away: "PHI", home: "CIN"},
		{spread: -7.5, away: "NO", home: "LAC"},
		{spread: 3, away: "BUF", home: "SEA"},
		{spread: 2.5, away: "CHI", home: "WSH"},
		{spread: -10, away: "CAR", home: "DEN"},
		{spread: 9.5, away: "KC", home: "LV"},
		{spread: -4, away: "DAL", home: "SF"},
		{spread: -6, away: "NYG", home: "PIT"},
	],
	[
		{spread: -3, away: "NE", home: "TEN"},
		{spread: 1, away: "LAC", home: "CLE"},
		{spread: 7.5, away: "NO", home: "CAR"},
		{spread: -6.5, away: "MIA", home: "BUF"},
		{spread: -3.5, away: "DAL", home: "ATL"},
		{spread: -9, away: "DEN", home: "BAL"},
		{spread: -7, away: "LV", home: "CIN"},
		{spread: 3.5, away: "WSH", home: "NYG"},
		{spread: -1.5, away: "CHI", home: "ARI"},
		{spread: -7.5, away: "JAX", home: "PHI"},
		{spread: 1.5, away: "LAR", home: "SEA"},
		{spread: 2.5, away: "DET", home: "GB"},
		{spread: -5, away: "IND", home: "MIN"},
		{spread: -9, away: "TB", home: "KC"},
	],
	[
		{"spread": 6.5, "away": "NYG", "home": "CAR"},
		{"spread": -6.0, "away": "NE", "home": "CHI"},
		{"spread": 4.0, "away": "BUF", "home": "IND"},
		{"spread": -7.5, "away": "DEN", "home": "KC"},
		{"spread": 3.5, "away": "ATL", "home": "NO"},
		{"spread": 6.5, "away": "SF", "home": "TB"},
		{"spread": -2.5, "away": "PIT", "home": "WSH"},
		{"spread": 7.0, "away": "MIN", "home": "JAX"},
		{"spread": -7.5, "away": "TEN", "home": "LAC"},
		{"spread": 7.0, "away": "PHI", "home": "DAL"},
		{"spread": 1.5, "away": "NYJ", "home": "ARI"},
		{"spread": 3.5, "away": "DET", "home": "HOU"},
		{"spread": -1.0, "away": "MIA", "home": "LAR"}
	],
	[
		{"spread": 5.5, "away": "GB", "home": "CHI"},
		{"spread": -13.5, "away": "JAX", "home": "DET"},
		{"spread": 6.0, "away": "MIN", "home": "TEN"},
		{"spread": -7.0, "away": "LV", "home": "MIA"},
		{"spread": 4.5, "away": "LAR", "home": "NE"},
		{"spread": 1.0, "away": "CLE", "home": "NO"},
		{"spread": -4.0, "away": "IND", "home": "NYJ"},
		{"spread": 3.0, "away": "BAL", "home": "PIT"},
		{"spread": -2.0, "away": "ATL", "home": "DEN"},
		{"spread": -6.5, "away": "SEA", "home": "SF"},
		{"spread": -2.0, "away": "KC", "home": "BUF"},
		{"spread": -1.5, "away": "CIN", "home": "LAC"},
		{"spread": 7.5, "away": "HOU", "home": "DAL"}
	],
	[
		{"spread": 3.5, "away": "MIN", "home": "CHI"},
		{"spread": 7.0, "away": "DET", "home": "IND"},
		{"spread": -7.5, "away": "NE", "home": "MIA"},
		{"spread": 6.0, "away": "TB", "home": "NYG"},
		{"spread": -10.5, "away": "DAL", "home": "WSH"},
		{"spread": 10.5, "away": "KC", "home": "CAR"},
		{"spread": -7.5, "away": "TEN", "home": "HOU"},
		{"spread": 6.0, "away": "DEN", "home": "LV"},
		{"spread": -3.0, "away": "SF", "home": "GB"},
		{"spread": 1.0, "away": "ARI", "home": "SEA"},
		{"spread": 3.0, "away": "PHI", "home": "LAR"},
		{"spread": 3.0, "away": "BAL", "home": "LAC"}
	],
	[
		{"spread": -9.5, "away": "CHI", "home": "DET"},
		{"spread": -3.5, "away": "NYG", "home": "DAL"},
		{"spread": -3.5, "away": "MIA", "home": "GB"},
		{"spread": -13.0, "away": "LV", "home": "KC"},
		{"spread": 1.5, "away": "LAC", "home": "ATL"},
		{"spread": -3.0, "away": "PIT", "home": "CIN"},
		{"spread": -3.5, "away": "ARI", "home": "MIN"},
		{"spread": 2.5, "away": "IND", "home": "NE"},
		{"spread": 2.0, "away": "SEA", "home": "NYJ"},
		{"spread": -5.5, "away": "TEN", "home": "WSH"},
		{"spread": 4.0, "away": "HOU", "home": "JAX"},
		{"spread": 2.5, "away": "LAR", "home": "NO"},
		{"spread": 5.5, "away": "TB", "home": "CAR"},
		{"spread": -3.0, "away": "PHI", "home": "BAL"},
		{"spread": -7.0, "away": "SF", "home": "BUF"},
		{"spread": -5.5, "away": "CLE", "home": "DEN"}
	  ]
]

export const weekIdToWeekNumber: string[] = [
	"5",
	"6",
	"7",
	"8",
	"9",
	"10",
	"11",
	"12",
	"13"
]
