import { Game } from '../components/GamePicker'

export const games: Game[][] = [
	[
		{"spread": 1.5, "away": "TB", "home": "ATL"},
		{"spread": 5.5, "away": "CIN", "home": "CLE"},
		{"spread": -1.5, "away": "MIA", "home": "IND"},
		{"spread": -2.5, "away": "LV", "home": "NE"},
		{"spread": 6.5, "away": "ARI", "home": "NO"},
		{"spread": 2.5, "away": "PIT", "home": "NYJ"},
		{"spread": -6.5, "away": "NYG", "home": "WSH"},
		{"spread": -3.5, "away": "CAR", "home": "JAX"},
		{"spread": -8.5, "away": "TEN", "home": "DEN"},
		{"spread": 1.5, "away": "SF", "home": "SEA"},
		{"spread": -1.5, "away": "DET", "home": "GB"},
		{"spread": -3.5, "away": "HOU", "home": "LAR"},
		{"spread": 1.5, "away": "BAL", "home": "BUF"},
		{"spread": 1.5, "away": "MIN", "home": "CHI"}
	],
	[
		{"spread": -3.5, "away": "JAX", "home": "CIN"},
		{"spread": -5.5, "away": "NYG", "home": "DAL"},
		{"spread": -6.5, "away": "CHI", "home": "DET"},
		{"spread": 5.5, "away": "LAR", "home": "TEN"},
		{"spread": -1.5, "away": "NE", "home": "MIA"},
		{"spread": 2.5, "away": "SF", "home": "NO"},
		{"spread": 6.5, "away": "BUF", "home": "NYJ"},
		{"spread": -3.5, "away": "SEA", "home": "PIT"},
		{"spread": -11.5, "away": "CLE", "home": "BAL"},
		{"spread": 1.5, "away": "DEN", "home": "IND"},
		{"spread": -6.5, "away": "CAR", "home": "ARI"},
		{"spread": 1.5, "away": "PHI", "home": "KC"},
		{"spread": -3.5, "away": "ATL", "home": "MIN"},
		{"spread": -2.5, "away": "TB", "home": "HOU"},
		{"spread": 3.5, "away": "LAC", "home": "LV"}
	],
	[
		{"spread": 7.5, "away": "GB", "home": "CLE"},
		{"spread": 4.5, "away": "IND", "home": "TEN"},
		{"spread": -2.5, "away": "CIN", "home": "MIN"},
		{"spread": 2.5, "away": "PIT", "home": "NE"},
		{"spread": -3.5, "away": "LAR", "home": "PHI"},
		{"spread": -6.5, "away": "NYJ", "home": "TB"},
		{"spread": -2.5, "away": "LV", "home": "WSH"},
		{"spread": 5.5, "away": "ATL", "home": "CAR"},
		{"spread": -1.5, "away": "HOU", "home": "JAX"},
		{"spread": -2.5, "away": "DEN", "home": "LAC"},
		{"spread": -7.5, "away": "NO", "home": "SEA"},
		{"spread": 1.5, "away": "DAL", "home": "CHI"},
		{"spread": -1.5, "away": "ARI", "home": "SF"},
		{"spread": 6.5, "away": "KC", "home": "NYG"},
		{"spread": -4.5, "away": "DET", "home": "BAL"}
	],
	[
		{"spread": 2.5, "away": "MIN", "home": "PIT"},
		{"spread": -1.5, "away": "WSH", "home": "ATL"},
		{"spread": -15.5, "away": "NO", "home": "BUF"},
		{"spread": -9.5, "away": "CLE", "home": "DET"},
		{"spread": -5.5, "away": "CAR", "home": "NE"},
		{"spread": 6.5, "away": "LAC", "home": "NYG"},
		{"spread": 3.5, "away": "PHI", "home": "TB"},
		{"spread": -7.5, "away": "TEN", "home": "HOU"},
		{"spread": -3.5, "away": "IND", "home": "LAR"},
		{"spread": -3.5, "away": "JAX", "home": "SF"},
		{"spread": 2.5, "away": "BAL", "home": "KC"},
		{"spread": -1.5, "away": "CHI", "home": "LV"},
		{"spread": 6.5, "away": "GB", "home": "DAL"},
		{"spread": -2.5, "away": "NYJ", "home": "MIA"},
		{"spread": -8.5, "away": "CIN", "home": "DEN"}
	],
	[
		{"spread": 3.5, "away": "MIN", "home": "CLE"},
		{"spread": -6.5, "away": "LV", "home": "IND"},
		{"spread": -2.5, "away": "NYG", "home": "NO"},
		{"spread": 1.5, "away": "DAL", "home": "NYJ"},
		{"spread": -4.5, "away": "DEN", "home": "PHI"},
		{"spread": 1.5, "away": "MIA", "home": "CAR"},
		{"spread": 1.5, "away": "HOU", "home": "BAL"},
		{"spread": -7.5, "away": "TEN", "home": "ARI"},
		{"spread": -3.5, "away": "TB", "home": "SEA"},
		{"spread": 9.5, "away": "DET", "home": "CIN"},
		{"spread": -2.5, "away": "WSH", "home": "LAC"},
		{"spread": -8.5, "away": "NE", "home": "BUF"},
		{"spread": 3.5, "away": "KC", "home": "JAX"}
	],
	[
		{"spread": 6.5, "away": "DEN", "home": "NYJ"},
		{"spread": -7.5, "away": "ARI", "home": "IND"},
		{"spread": 3.5, "away": "LAC", "home": "MIA"},
		{"spread": 3.5, "away": "NE", "home": "NO"},
		{"spread": -6.5, "away": "CLE", "home": "PIT"},
		{"spread": 3.5, "away": "DAL", "home": "CAR"},
		{"spread": 1.5, "away": "SEA", "home": "JAX"},
		{"spread": 7.5, "away": "LAR", "home": "BAL"},
		{"spread": -3.5, "away": "TEN", "home": "LV"},
		{"spread": -14.5, "away": "CIN", "home": "GB"},
		{"spread": -3.5, "away": "SF", "home": "TB"},
		{"spread": -2.5, "away": "DET", "home": "KC"},
		{"spread": 4.5, "away": "BUF", "home": "ATL"},
		{"spread": -4.5, "away": "CHI", "home": "WSH"}
	],
	[
		{"spread": 3.5, "away": "LAR", "home": "JAX"},
		{"spread": -3.5, "away": "NO", "home": "CHI"},
		{"spread": -2.5, "away": "MIA", "home": "CLE"},
		{"spread": 6.5, "away": "NE", "home": "TEN"},
		{"spread": -11.5, "away": "LV", "home": "KC"},
		{"spread": 2.5, "away": "PHI", "home": "MIN"},
		{"spread": 1.5, "away": "CAR", "home": "NYJ"},
		{"spread": -7.5, "away": "NYG", "home": "DEN"},
		{"spread": -2.5, "away": "IND", "home": "LAC"},
		{"spread": -1.5, "away": "WSH", "home": "DAL"},
		{"spread": 7.5, "away": "GB", "home": "ARI"},
		{"spread": -2.5, "away": "ATL", "home": "SF"},
		{"spread": -6.5, "away": "TB", "home": "DET"},
		{"spread": -3.5, "away": "HOU", "home": "SEA"}
	],
	[
		{"spread": -6.5, "away": "MIA", "home": "ATL"},
		{"spread": -6.5, "away": "NYJ", "home": "CIN"},
		{"spread": -6.5, "away": "CLE", "home": "NE"},
		{"spread": -7.5, "away": "NYG", "home": "PHI"},
		{"spread": 7.5, "away": "BUF", "home": "CAR"},
		{"spread": -2.5, "away": "CHI", "home": "BAL"},
		{"spread": -2.5, "away": "SF", "home": "HOU"},
		{"spread": 3.5, "away": "TB", "home": "NO"},
		{"spread": -3.5, "away": "DAL", "home": "DEN"},
		{"spread": -14.5, "away": "TEN", "home": "IND"},
		{"spread": 2.5, "away": "GB", "home": "PIT"},
		{"spread": -11.5, "away": "WSH", "home": "KC"}
	],
	[
		{"spread": 2.5, "away": "CHI", "home": "CIN"},
		{"spread": -8.5, "away": "MIN", "home": "DET"},
		{"spread": -13.5, "away": "CAR", "home": "GB"},
		{"spread": 9.5, "away": "LAC", "home": "TEN"},
		{"spread": -4.5, "away": "ATL", "home": "NE"},
		{"spread": 2.5, "away": "SF", "home": "NYG"},
		{"spread": 3.5, "away": "IND", "home": "PIT"},
		{"spread": -2.5, "away": "DEN", "home": "HOU"},
		{"spread": 2.5, "away": "JAX", "home": "LV"},
		{"spread": -14.5, "away": "NO", "home": "LAR"},
		{"spread": 1.5, "away": "KC", "home": "BUF"},
		{"spread": 2.5, "away": "SEA", "home": "WSH"},
		{"spread": -3.5, "away": "ARI", "home": "DAL"}
	  ]
]

export const weekIdToWeekNumber: string[] = [
	"1",
	"2",
	"3",
	"4",
	"5",
	"6",
	"7",
	"8",
	"9"
]
